# datasource configuration
quarkus:
  datasource:
    db-kind: h2
    username: sa
    #password:
    jdbc:
      url: jdbc:h2:mem:test
  hibernate-orm:
    database:
      generation: drop-and-create
    sql-load-script: 'db/data.sql'